# Copyright 2021 RUVU Robotics B.V.

---
include:
  - project: ruvu/environment
    file: ROS.gitlab-ci.yml

variables:
  WORKSPACE: project-mcl
  PACKAGES: >
    mir_mcl
    ruvu_mcl
    ruvu_mcl_landmark_server
    ruvu_mcl_msgs
    turtlebot3_mcl

stages:
  - lint
  - build
  - test
  - release

clang-format:
  stage: lint
  image:
    name: witekio/clang-format-checker
    entrypoint: [""]
  before_script: []
  script:
    - run-clang-format.py -r .

melodic-build-on-schedule:
  extends: .build-on-schedule
  variables:
    ROS_DISTRO: melodic
melodic-build:
  extends: .build
  variables:
    ROS_DISTRO: melodic
melodic-test:
  extends: .test
  variables:
    ROS_DISTRO: melodic
melodic-release:
  extends: .release
  variables:
    ROS_DISTRO: melodic

noetic-build-on-schedule:
  extends: .build-on-schedule
  variables:
    ROS_DISTRO: noetic
noetic-build:
  extends: .build
  variables:
    ROS_DISTRO: noetic
noetic-test:
  extends: .test
  variables:
    ROS_DISTRO: noetic
noetic-release:
  extends: .release
  variables:
    ROS_DISTRO: noetic

